### ISSUE TITLE
Salomon Out of date #CONDA#

### ISSUE THREAD

**Issue by edgano** [JoseEspinosa/BovReg-Reproducibility#1]
With this env receipt:
```
name: rnaseq-nf
channels:
  - defaults
  - bioconda
  - conda-forge
dependencies:
  # Default bismark
  - notebook=5.7.8
  - salmon=1.0.0
  - fastqc=0.11.5
  - multiqc=1.5
```
Salomon informs about a new version
![Screenshot 2020-04-09 at 17 53 47](https://user-images.githubusercontent.com/4262262/78914830-4a12a480-7a8b-11ea-8dd9-096058b5e1a3.png)

**Comment by JoseEspinosa** [comment]
Closed with 1b382ccf0f59e80be621ca668c27a9f5989fab5c
